const K='tlp48_db_v3';
const S={settings:{name:'TLP48',hero:'Welcome to TLP48'},users:[{id:1,name:'TLP48 Fan',email:'fan@tlp48.com',password:'123456',role:'user',coins:2500}],members:[],singles:[],products:[{id:1,name:'TLP48 Photo Set',price:300,stock:48},{id:2,name:'TLP48 Acrylic Stand',price:1200,stock:20},{id:3,name:'TLP48 T-Shirt',price:2000,stock:15}],orders:[],redeems:[]};
function D(){try{return JSON.parse(localStorage.getItem(K))||S}catch(e){return S}} function W(d){localStorage.setItem(K,JSON.stringify(d))} function U(){return D().users.find(u=>u.id==localStorage.getItem('tlp48_user'))} function E(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function nav(a){return `<header class="top"><nav class="nav"><a class="brand" href="index.html">🌷 TLP48</a><div class="navlinks"><a class="${a=='members'?'active':''}" href="members.html">MEMBERS</a><a class="${a=='single'?'active':''}" href="single.html">SINGLE</a><a class="${a=='shop'?'active':''}" href="shop.html">MERCHANDISE</a><a class="${a=='coins'?'active':''}" href="token.html">TULIPS COINS</a>${U()?`<a href="profile.html">👤 ${E(U().name)}</a><a href="#" onclick="logout()">LOGOUT</a>`:`<a href="login.html">LOGIN</a>`}</div></nav></header>`}
function shell(a,b){document.getElementById('app').innerHTML=nav(a)+`<main class="container">${b}</main><footer class="footer">🌷 TLP48 • TULIPS COINS</footer>`}
function home(){shell('',`<section class="hero"><div><span class="pill">TLP48 OFFICIAL FAN APP</span><h1>Welcome to TLP48</h1><p>เว็บไซต์ TLP48 ธีมดอกไม้ ฟ้า–ขาว</p><div class="actions"><a class="btn" href="members.html">MEMBERS</a><a class="btn secondary" href="shop.html">MERCHANDISE</a></div></div><div class="flower-card">🌷</div></section><div class="grid">${[['👥','MEMBERS','members.html'],['🎵','SINGLE','single.html'],['🛍️','MERCHANDISE','shop.html'],['🪙','TULIPS COINS','token.html']].map(x=>`<a class="card" href="${x[2]}"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p class="muted">เข้าสู่ ${x[1]}</p></a>`).join('')}</div>`)}
function members(){let d=D();shell('members',`<h2>MEMBERS</h2>${[1,2,3,4].map(g=>`<section><div class="section-title"><h2>Generation ${g}</h2></div><div class="grid grid3">${d.members.filter(m=>+m.gen===g).map(m=>`<a class="card" href="member.html?id=${m.id}"><div class="flower-card" style="min-height:180px;font-size:65px">🌷</div><h3>${E(m.name)}</h3><span class="pill">GEN ${g}</span></a>`).join('')||'<div class="card empty">ยังไม่มีข้อมูลสมาชิก</div>'}</div></section>`).join('')}`)}
function singles(){let d=D();shell('single',`<h2>SINGLE</h2><div class="grid grid3">${d.singles.map(s=>`<article class="card"><div class="flower-card" style="min-height:180px">🌷</div><h3>${E(s.name)}</h3><p class="muted">${E(s.detail||'TLP48 Single')}</p></article>`).join('')||'<div class="card empty">ยังไม่มีข้อมูล Single</div>'}</div>`)}
function shop(){let d=D();shell('shop',`<div class="section-title"><h2>MERCHANDISE</h2><span class="pill">${U()?U().coins.toLocaleString():'—'} TULIPS COINS</span></div><div class="grid grid3">${d.products.map(p=>`<article class="card"><div class="flower-card" style="min-height:180px">🌷</div><h3>${E(p.name)}</h3><p class="price">🪙 ${p.price.toLocaleString()} TULIPS COINS</p><p class="muted">เหลือ ${p.stock}</p><button class="btn" onclick="buy(${p.id})">ซื้อ</button></article>`).join('')}</div>`)}
function buy(id){let u=U();if(!u)return location.href='login.html';let d=D(),p=d.products.find(x=>x.id==id);if(!p||p.stock<1)return alert('สินค้าหมด');if(u.coins<p.price)return alert('TULIPS COINS ไม่พอ');u.coins-=p.price;p.stock--;d.orders.push({id:Date.now(),userId:u.id,product:p.name,price:p.price,status:'รอดำเนินการ'});W(d);alert('สั่งซื้อสำเร็จ');shop()}
function coins(){let u=U();shell('coins',`<div class="card"><span class="pill">MY TULIPS COINS</span><div class="stat">${u?u.coins.toLocaleString():'0'} 🪙</div></div><div class="card form"><h2>Redeem Code</h2><div class="field"><label>Redeem Code</label><input id="rc" placeholder="TLP48-XXXX-XXXX"></div><button class="btn" onclick="redeem()">REDEEM</button></div>`)}
function redeem(){let u=U();if(!u)return location.href='login.html';let d=D(),r=d.redeems.find(x=>x.code===rc.value.trim()&&!x.used);if(!r)return alert('Code ไม่ถูกต้องหรือใช้แล้ว');r.used=true;u.coins+=r.coins;W(d);alert(`ได้รับ ${r.coins.toLocaleString()} TULIPS COINS`);coins()}
function login(){document.getElementById('app').innerHTML=`<main class="container"><form class="card form" onsubmit="doLogin(event)"><div class="brand">🌷 TLP48</div><h2>LOGIN</h2><div class="field"><label>Email</label><input id="em" type="email" required></div><div class="field"><label>Password</label><input id="pw" type="password" required></div><button class="btn">เข้าสู่ระบบ</button><p class="muted">ทดลอง: fan@tlp48.com / 123456</p></form></main>`}
function doLogin(e){e.preventDefault();let u=D().users.find(x=>x.email===em.value&&x.password===pw.value);if(!u)return alert('ข้อมูลเข้าสู่ระบบไม่ถูกต้อง');localStorage.setItem('tlp48_user',u.id);location.href='index.html'} function logout(){localStorage.removeItem('tlp48_user');location.href='index.html'}
function profile(){let u=U();if(!u)return location.href='login.html';shell('',`<div class="card"><h2>PROFILE</h2><h3>${E(u.name)}</h3><p>${E(u.email)}</p><div class="stat">🪙 ${u.coins.toLocaleString()}</div><a class="btn" href="orders.html">ORDERS</a></div>`)}
function orders(){let u=U();if(!u)return location.href='login.html';let d=D();shell('',`<h2>ORDERS</h2><div class="table-wrap"><table class="table"><tr><th>สินค้า</th><th>ราคา</th><th>สถานะ</th></tr>${d.orders.filter(o=>o.userId==u.id).map(o=>`<tr><td>${E(o.product)}</td><td>🪙 ${o.price}</td><td>${E(o.status)}</td></tr>`).join('')||'<tr><td colspan="3">ยังไม่มีคำสั่งซื้อ</td></tr>'}</table></div>`)}
function member(){let id=new URLSearchParams(location.search).get('id'),m=D().members.find(x=>x.id==id);shell('members',m?`<div class="card"><div class="flower-card">🌷</div><h1>${E(m.name)}</h1><span class="pill">GEN ${m.gen}</span><p>${E(m.bio||'')}</p></div>`:'<div class="card empty">ไม่พบสมาชิก</div>')}
function admin(){let u=U();if(!u||u.role!=='admin')return location.href='login.html';let d=D();shell('',`<h2>ADMIN / BACK OFFICE</h2><div class="grid"><div class="card"><h3>Users</h3><div class="stat">${d.users.length}</div></div><div class="card"><h3>Members</h3><div class="stat">${d.members.length}</div></div><div class="card"><h3>Products</h3><div class="stat">${d.products.length}</div></div><div class="card"><h3>Orders</h3><div class="stat">${d.orders.length}</div></div></div><div class="card form"><h3>สร้าง Redeem Code</h3><input id="code" placeholder="TLP48-WELCOME"><input id="amount" type="number" placeholder="Coins" style="margin:10px 0"><button class="btn" onclick="makeCode()">สร้าง</button></div>`)}
function makeCode(){let d=D();if(!code.value||!amount.value)return alert('กรอกข้อมูลให้ครบ');d.redeems.push({code:code.value.trim(),coins:+amount.value,used:false});W(d);alert('สร้าง Code แล้ว');admin()}
function route(){let p=location.pathname.split('/').pop()||'index.html';if(p==='index.html')home();else if(p==='members.html')members();else if(p==='single.html')singles();else if(p==='shop.html')shop();else if(p==='token.html')coins();else if(p==='login.html')login();else if(p==='profile.html')profile();else if(p==='orders.html')orders();else if(p==='member.html')member();else if(p==='admin.html')admin();else home()}
window.buy=buy;window.redeem=redeem;window.doLogin=doLogin;window.logout=logout;window.makeCode=makeCode;route();
